/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.Color;

/**
 *
 * @author oswaldo
 */
public class Persona extends javax.swing.JPanel {

    /**
     * Creates new form Persona
     */
    public Persona() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        consolaPersona = new javax.swing.JTextPane();
        guardarPersona = new javax.swing.JButton();
        nombrePersona = new javax.swing.JTextField();
        clavePersona = new javax.swing.JTextField();
        telefonoPersona = new javax.swing.JTextField();
        direccionPersona = new javax.swing.JTextField();
        buscarPersona = new javax.swing.JButton();
        editarPersona = new javax.swing.JButton();
        borrarPersona = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        regresar = new javax.swing.JButton();

        jScrollPane1.setViewportView(consolaPersona);

        guardarPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Guardar.png"))); // NOI18N
        guardarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarPersonaActionPerformed(evt);
            }
        });

        nombrePersona.setForeground(new java.awt.Color(153, 153, 153));
        nombrePersona.setText("Nombre:");
        nombrePersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nombrePersonaMouseClicked(evt);
            }
        });

        clavePersona.setForeground(new java.awt.Color(153, 153, 153));
        clavePersona.setText("Clave:");
        clavePersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clavePersonaMouseClicked(evt);
            }
        });

        telefonoPersona.setForeground(new java.awt.Color(153, 153, 153));
        telefonoPersona.setText("Telefono:");
        telefonoPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                telefonoPersonaMouseClicked(evt);
            }
        });

        direccionPersona.setForeground(new java.awt.Color(153, 153, 153));
        direccionPersona.setText("Direccion:");
        direccionPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                direccionPersonaMouseClicked(evt);
            }
        });

        buscarPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Buscar.png"))); // NOI18N

        editarPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Editar.png"))); // NOI18N

        borrarPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Eliminar.png"))); // NOI18N

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PERSONA");

        regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Regresar.png"))); // NOI18N
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(borrarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guardarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(clavePersona, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nombrePersona, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(telefonoPersona, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(direccionPersona)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buscarPersona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editarPersona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(borrarPersona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(regresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(guardarPersona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(clavePersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombrePersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telefonoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(direccionPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nombrePersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombrePersonaMouseClicked
        nombrePersona.setText("");
        nombrePersona.setBackground(Color.BLACK);
    }//GEN-LAST:event_nombrePersonaMouseClicked

    private void clavePersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clavePersonaMouseClicked
        clavePersona.setText("");
        clavePersona.setBackground(Color.BLACK);
    }//GEN-LAST:event_clavePersonaMouseClicked

    private void telefonoPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_telefonoPersonaMouseClicked
        telefonoPersona.setText("");
        telefonoPersona.setBackground(Color.BLACK);
    }//GEN-LAST:event_telefonoPersonaMouseClicked

    private void direccionPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_direccionPersonaMouseClicked
        direccionPersona.setText("");
        direccionPersona.setBackground(Color.BLACK);
    }//GEN-LAST:event_direccionPersonaMouseClicked

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_regresarActionPerformed

    private void guardarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarPersonaActionPerformed
        clavePersona.setBackground(Color.DARK_GRAY);
        clavePersona.setText("Clave:");

        nombrePersona.setBackground(Color.DARK_GRAY);
        nombrePersona.setText("Nombre:");

        telefonoPersona.setBackground(Color.DARK_GRAY);
        telefonoPersona.setText("Telefono:");

        direccionPersona.setBackground(Color.DARK_GRAY);
        direccionPersona.setText("Direccion:");
    }//GEN-LAST:event_guardarPersonaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrarPersona;
    private javax.swing.JButton buscarPersona;
    private javax.swing.JTextField clavePersona;
    private javax.swing.JTextPane consolaPersona;
    private javax.swing.JTextField direccionPersona;
    private javax.swing.JButton editarPersona;
    private javax.swing.JButton guardarPersona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombrePersona;
    private javax.swing.JButton regresar;
    private javax.swing.JTextField telefonoPersona;
    // End of variables declaration//GEN-END:variables
}
