/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import DAO.Departamento;
import DAO.FactoryDAO;
import DAO.IDAOGeneral;
import DAO.Persona;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author oswaldo
 */
public class Personas extends javax.swing.JPanel {

    /**
     * Creates new form Persona
     */
    public Personas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        consolaPersona = new javax.swing.JTextPane();
        guardarPersona = new javax.swing.JButton();
        nombrePersona = new javax.swing.JTextField();
        clavePersona = new javax.swing.JTextField();
        telefonoPersona = new javax.swing.JTextField();
        direccionPersona = new javax.swing.JTextField();
        buscarPersona = new javax.swing.JButton();
        editarPersona = new javax.swing.JButton();
        borrarPersona = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        regresar = new javax.swing.JButton();
        departamentoPersona = new javax.swing.JTextField();

        jScrollPane1.setViewportView(consolaPersona);

        guardarPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Guardar.png"))); // NOI18N
        guardarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarPersonaActionPerformed(evt);
            }
        });

        nombrePersona.setForeground(new java.awt.Color(153, 153, 153));
        nombrePersona.setText("Nombre:");
        nombrePersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nombrePersonaMouseClicked(evt);
            }
        });

        clavePersona.setForeground(new java.awt.Color(153, 153, 153));
        clavePersona.setText("Clave:");
        clavePersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clavePersonaMouseClicked(evt);
            }
        });

        telefonoPersona.setForeground(new java.awt.Color(153, 153, 153));
        telefonoPersona.setText("Telefono:");
        telefonoPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                telefonoPersonaMouseClicked(evt);
            }
        });

        direccionPersona.setForeground(new java.awt.Color(153, 153, 153));
        direccionPersona.setText("Direccion:");
        direccionPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                direccionPersonaMouseClicked(evt);
            }
        });

        buscarPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Buscar.png"))); // NOI18N
        buscarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPersonaActionPerformed(evt);
            }
        });

        editarPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Editar.png"))); // NOI18N
        editarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarPersonaActionPerformed(evt);
            }
        });

        borrarPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Eliminar.png"))); // NOI18N
        borrarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarPersonaActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PERSONA");

        regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Regresar.png"))); // NOI18N
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });

        departamentoPersona.setForeground(new java.awt.Color(153, 153, 153));
        departamentoPersona.setText("Departamento:");
        departamentoPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                departamentoPersonaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(borrarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guardarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 35, Short.MAX_VALUE))
                    .addComponent(clavePersona)
                    .addComponent(nombrePersona)
                    .addComponent(telefonoPersona)
                    .addComponent(direccionPersona, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(departamentoPersona, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buscarPersona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editarPersona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(borrarPersona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(regresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(guardarPersona))
                .addGap(18, 18, 18)
                .addComponent(clavePersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombrePersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telefonoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(direccionPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(departamentoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nombrePersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombrePersonaMouseClicked
        nombrePersona.setText("");
        nombrePersona.setForeground(Color.BLACK);
    }//GEN-LAST:event_nombrePersonaMouseClicked

    private void clavePersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clavePersonaMouseClicked
        clavePersona.setText("");
        clavePersona.setForeground(Color.BLACK);
    }//GEN-LAST:event_clavePersonaMouseClicked

    private void telefonoPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_telefonoPersonaMouseClicked
        telefonoPersona.setText("");
        telefonoPersona.setForeground(Color.BLACK);
    }//GEN-LAST:event_telefonoPersonaMouseClicked

    private void direccionPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_direccionPersonaMouseClicked
        direccionPersona.setText("");
        direccionPersona.setForeground(Color.BLACK);
    }//GEN-LAST:event_direccionPersonaMouseClicked

    private void departamentoPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_departamentoPersonaMouseClicked
        departamentoPersona.setText("");
        departamentoPersona.setForeground(Color.BLACK);
    }//GEN-LAST:event_departamentoPersonaMouseClicked

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_regresarActionPerformed

    private void guardarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarPersonaActionPerformed
        consolaPersona.setText("");
        IDAOGeneral daop = FactoryDAO.create(FactoryDAO.TypeDAO.PERSONA);
        Persona d = new Persona();
        IDAOGeneral daod = FactoryDAO.create(FactoryDAO.TypeDAO.DEPARTAMENTO);
        Departamento p = new Departamento();

        d.setClave(clavePersona.getText());
        d.setNombre(nombrePersona.getText());
        d.setDireccion(direccionPersona.getText());
        d.setTelefono(telefonoPersona.getText());
        Departamento depto = new Departamento();
        depto.setClave(departamentoPersona.getText());
        ResultSet rs = daod.buscar(depto);
        
        try {
            rs.next();
        } catch (SQLException ex) {
            Logger.getLogger(Personas.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            depto.setClave(rs.getString(1));
        } catch (SQLException ex) {
            Logger.getLogger(Personas.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            depto.setNombre(rs.getString(2));
        } catch (SQLException ex) {
            Logger.getLogger(Personas.class.getName()).log(Level.SEVERE, null, ex);
        }
        d.setDepartamento(depto);
        formato();
        if (daop.guardar(d)) {
            consolaPersona.setText("guardado");
        } else {
            consolaPersona.setText("NO se pudo guardar");
        }
    }//GEN-LAST:event_guardarPersonaActionPerformed

    private void buscarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPersonaActionPerformed
        consolaPersona.setText("");
        IDAOGeneral daop = FactoryDAO.create(FactoryDAO.TypeDAO.PERSONA);
        Persona d = new Persona();

        d.setClave(clavePersona.getText());
        ResultSet rs = daop.buscar(d);
        boolean st = false;
        try {
            st = rs.next();
        } catch (SQLException ex) {
            Logger.getLogger(Personas.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (st) {
            try {
                consolaPersona.setText("encontrado");
                clavePersona.setText(rs.getString(1));
                nombrePersona.setText(rs.getString(2));
                direccionPersona.setText(rs.getString(3));
                departamentoPersona.setText(rs.getString(5));
                telefonoPersona.setText(rs.getString(4));
            } catch (SQLException ex) {
                Logger.getLogger(Personas.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            consolaPersona.setText("NO se pudo encontrar");
        }    }//GEN-LAST:event_buscarPersonaActionPerformed

    private void editarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarPersonaActionPerformed
        consolaPersona.setText("");
        IDAOGeneral daop = FactoryDAO.create(FactoryDAO.TypeDAO.PERSONA);
        Persona d = new Persona();
        IDAOGeneral daod = FactoryDAO.create(FactoryDAO.TypeDAO.DEPARTAMENTO);
        Departamento p = new Departamento();

        d.setClave(clavePersona.getText());
        d.setNombre(nombrePersona.getText());
        d.setDireccion(direccionPersona.getText());
        d.setTelefono(telefonoPersona.getText());
        Departamento depto = new Departamento();
        depto.setClave(departamentoPersona.getText());
        ResultSet rs = daop.buscar(depto);
        try {
            rs.next();
        } catch (SQLException ex) {
            Logger.getLogger(Personas.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            depto.setClave(rs.getString(1));
        } catch (SQLException ex) {
            Logger.getLogger(Personas.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            depto.setNombre(rs.getString(2));
        } catch (SQLException ex) {
            Logger.getLogger(Personas.class.getName()).log(Level.SEVERE, null, ex);
        }
        d.setDepartamento(depto);
        formato();
        if (daop.editar(d)) {
            consolaPersona.setText("guardado");
        } else {
            consolaPersona.setText("NO se pudo guardar");
        }    }//GEN-LAST:event_editarPersonaActionPerformed

    private void borrarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarPersonaActionPerformed
        consolaPersona.setText("");
        IDAOGeneral daop = FactoryDAO.create(FactoryDAO.TypeDAO.PERSONA);
        Persona d = new Persona();
        d.setClave(clavePersona.getText());
        formato();
        if (daop.eliminar(d)) {
            consolaPersona.setText("eliminar");
        } else {
            consolaPersona.setText("NO se pudo eliminar");
        }    }//GEN-LAST:event_borrarPersonaActionPerformed

    private void formato() {
        consolaPersona.setText("");

        clavePersona.setForeground(Color.DARK_GRAY);
        clavePersona.setText("Clave:");

        nombrePersona.setForeground(Color.DARK_GRAY);
        nombrePersona.setText("Nombre:");

        telefonoPersona.setForeground(Color.DARK_GRAY);
        telefonoPersona.setText("Telefono:");

        direccionPersona.setForeground(Color.DARK_GRAY);
        direccionPersona.setText("Direccion:");

        departamentoPersona.setForeground(Color.DARK_GRAY);
        departamentoPersona.setText("Departamento: ");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrarPersona;
    private javax.swing.JButton buscarPersona;
    private javax.swing.JTextField clavePersona;
    private javax.swing.JTextPane consolaPersona;
    private javax.swing.JTextField departamentoPersona;
    private javax.swing.JTextField direccionPersona;
    private javax.swing.JButton editarPersona;
    private javax.swing.JButton guardarPersona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombrePersona;
    private javax.swing.JButton regresar;
    private javax.swing.JTextField telefonoPersona;
    // End of variables declaration//GEN-END:variables
}
